sudo: required
dist: trusty
git:
  depth: 1
# https://github.com/hvr/multi-ghc-travis
addons:
  apt:
    sources: hvr-ghc
    packages:
      - cabal-install-1.24
      - ghc-7.10.3
      - alex-3.1.7
      - happy-1.19.5
language: node_js
branches:
  except: /^v\d/
node_js:
  - node
  - 4
before_install:
  - export PATH="/opt/ghc/7.10.3/bin:$PATH"
  - export PATH="/opt/cabal/1.24/bin:$PATH"
  - export PATH="$HOME/.cabal/bin:$PATH"
  - export PATH="/opt/happy/1.19.5/bin:/$PATH"
  - export PATH="/opt/alex/3.1.7/bin:/$PATH"
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
script: npm run-script pretest && travis_wait npm run-script coverage
after_script:
  - npm install istanbul-coveralls
  - node node_modules/.bin/istanbul-coveralls
notifications:
  email: false
