dist: trusty
git:
  depth: 1
cache:
  directories:
    - $HOME/.stack
language: node_js
branches:
  except: /^v\d/
node_js:
  - node
  - 4
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
script: npm run-script pretest && travis_wait 45 npm run-script coverage
after_script:
  - npm install istanbul-coveralls
  - node node_modules/.bin/istanbul-coveralls
